### PR TITLE
Enhancements for Enterprise SONiC Distribution Compatibility on Edgecore

### PR DESCRIPTION
**Pull request by robertvolkmann**
This pull request introduces the following minor tweaks to improve monsoon's compatibility with the Enterprise SONiC Distribution by Edgecore:

* Ensure bytes and packets are represented as floats to prevent TypeError
* Add support for non-password protected Redis instances

### CODE REVIEW

**Comment by kamalkrbh** [comment]
Thanks for your contributiuon, changes are now propagated to [live demo](http://monsoon.stordis.com:8080/).

**Comment by robertvolkmann** [comment]
@kamalkrbh Any plans for a new release?

**Comment by kamalkrbh** [comment]
@robertvolkmann , Perhaps Next week we will create a new release.
BTW, I see you are using monsoon on Edgecore SONiC, How it looks there, Are you able see all metrics?

**Comment by kamalkrbh** [comment]
> 

New release 1.1.0 created.

**Comment by robertvolkmann** [comment]
@kamalkrbh I'm able to see some metrics but not all.

**Pull request merged**
